#!/bin/sh

USER=''
HOST=''
PORT=''
DIR=''
METHOD=''
COMMAND=''
GIT_COMMAND='&& git pull'

case $1 in
  STAGING)
    USER=${TARGET_SERVER_STAGING_USER}
    HOST=${TARGET_SERVER_STAGING_HOST}
    PORT=${TARGET_SERVER_STAGING_PORT}
    DIR=${TARGET_SERVER_STAGING_DIR}
    METHOD=${DEPLOYMENT_METHOD_STAGING}
    if [ "${COMMAND_STAGING}" != "" ]; then COMMAND=" && ${COMMAND_STAGING}";fi;
    ;;
  RELEASE_CANDIDATE)
    USER=${TARGET_SERVER_RELEASE_CANDIDATE_USER}
    HOST=${TARGET_SERVER_RELEASE_CANDIDATE_HOST}
    PORT=${TARGET_SERVER_RELEASE_CANDIDATE_PORT}
    DIR=${TARGET_SERVER_RELEASE_CANDIDATE_DIR}
    METHOD=${DEPLOYMENT_METHOD_RELEASE_CANDIDATE}
    if [ "${COMMAND_RELEASE_CANDIDATE}" != "" ]; then COMMAND=" && ${COMMAND_RELEASE_CANDIDATE}";fi;
    GIT_COMMAND='&& git checkout -f && git checkout '${CI_COMMIT_REF_NAME}' && git pull'
    ;;
  PROD)
    USER=${TARGET_SERVER_PROD_USER}
    HOST=${TARGET_SERVER_PROD_HOST}
    PORT=${TARGET_SERVER_PROD_PORT}
    DIR=${TARGET_SERVER_PROD_DIR}
    METHOD=${DEPLOYMENT_METHOD_PROD}
    if [ "${COMMAND_PROD}" != "" ]; then COMMAND=" && ${COMMAND_PROD}";fi;
    ;;
esac

case $METHOD in
  git) ssh -p"${PORT}" "${USER}"@"${HOST}" 'cd '"${DIR}"' '${GIT_COMMAND}' '${COMMAND}'';;
  lftp) lftp -e "mirror -e -P 4 --transfer-all --reverse ${LFTP_ARGS} --verbose ./www/ ${DIR}; quit" -u ${USER},${PASSWORD} sftp://${HOST} -p ${PORT} ;;
esac